In [2]:
import pandas as pd

In [5]:
data=pd.read_csv('Final_Data.csv')
df=pd.DataFrame(data)
df

,Unnamed: 0,Year,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Cash Flow from Operations Growth(%)
0,0,2023,Microsoft,211915,72361,411976,205753,87582,0.00,0.00,0.00,0.00,0.00
1,1,2022,Microsoft,198270,72738,364840,198298,89035,-6.44,0.52,-11.44,-3.62,1.66
2,2,2021,Microsoft,168088,61271,333779,191791,76740,-15.22,-15.76,-8.51,-3.28,-13.81
3,3,2023,Tesla,96773,14974,106618,43009,13256,0.00,0.00,0.00,0.00,0.00
4,4,2022,Tesla,81462,12556,82338,36440,14724,-15.82,-16.15,-22.77,-15.27,11.07
5,5,2021,Tesla,53821,5519,62131,30548,11497,-33.93,-56.04,-24.54,-16.17,-21.92
6,6,2023,Apple,383285,96995,352583,290437,110543,0.00,0.00,0.00,0.00,0.00
7,7,2022,Apple,394328,99803,352755,302083,122151,2.88,2.89,0.05,4.01,10.50
8,8,2021,Apple,365817,94680,351002,287912,104038,-7.23,-5.13,-0.50,-4.69,-14.83

In [24]:
import pandas as pd

data = {}

# Iterate over unique companies
for company in df['Company'].unique():
    data[company] = {}
    company_data = df[df['Company'] == company]  # Filter data for the current company

    # Iterate over years
    for year in company_data['Year'].unique():
        year_data = company_data[company_data['Year'] == year].iloc[0]  # Get data for the year
        data[company][year] = year_data.drop(['Company', 'Year']).to_dict() # Include all other columns

print(data)
def financial_chatbot(company, year, metric):
    # Validate company and year
    if company in data and year in data[company]:
        # Retrieve the metric
        company_year_data = data[company][year]
        metric_value = company_year_data.get(metric)

        # Check if the metric exists for the given year
        if metric_value:
            return f"\n******************The {metric} for {company} in {year} is: {metric_value}**********\n"
        else:
            return f"Sorry, we don’t have data for '{metric}' for {company} in {year}."
    else:
        return f"Sorry, we don’t have data for {company} in {year}."

# Main loop to interact with the chatbot
print("Welcome to the AI-powered financial chatbot!")
print("We have fiscal data from 2021 to 2023 for Microsoft, Tesla, and Apple.")

while True:
    # Take user input
    company = input("Which company's data do you want?: ")
    year = int(input("Of which year?: "))

    print("1. Total Revenue")
    print("2. Total Net Income")
    print("3. Total Assets")
    print("4. Total Liabilities")
    print("5. Cash Flow from Operating Activities")
    print("6. Revenue Growth (%)")
    print("7. Net Income Growth (%)")

    metric_options = {
        "1": "Total Revenue",
        "2": "Total Net Income",
        "3": "Total Assets",
        "4": "Total Liabilities",
        "5": "Cash Flow from Operating Activities",
        "6": "Revenue Growth (%)",
        "7": "Net Income Growth (%)"
    }

    metric_choice = input("Enter the metric's number you want to know: ")
    metric = metric_options.get(metric_choice)

    # Call the chatbot function
    if metric:
        print(financial_chatbot(company, year, metric))
    else:
        print("Invalid choice. Please try again.")

    # Ask if the user wants to continue
    continue_choice = input("Do you want to continue (yes/no)?: ")
    if continue_choice.lower() == "no":
        break

print("Thank you!")

{'Microsoft': {2023: {'Unnamed: 0': 0, 'Total Revenue': 211915, 'Net Income': 72361, 'Total Assets': 411976, 'Total Liabilities': 205753, 'Cash Flow from Operating Activities': 87582, 'Revenue Growth (%)': 0.0, 'Net Income Growth (%)': 0.0, 'Assets Growth (%)': 0.0, 'Liabilities Growth (%)': 0.0, 'Cash Flow from Operations Growth(%)': 0.0}, 2022: {'Unnamed: 0': 1, 'Total Revenue': 198270, 'Net Income': 72738, 'Total Assets': 364840, 'Total Liabilities': 198298, 'Cash Flow from Operating Activities': 89035, 'Revenue Growth (%)': -6.44, 'Net Income Growth (%)': 0.52, 'Assets Growth (%)': -11.44, 'Liabilities Growth (%)': -3.62, 'Cash Flow from Operations Growth(%)': 1.66}, 2021: {'Unnamed: 0': 2, 'Total Revenue': 168088, 'Net Income': 61271, 'Total Assets': 333779, 'Total Liabilities': 191791, 'Cash Flow from Operating Activities': 76740, 'Revenue Growth (%)': -15.22, 'Net Income Growth (%)': -15.76, 'Assets Growth (%)': -8.51, 'Liabilities Growth (%)': -3.28, 'Cash Flow from Operations Growth(%)': -13.81}}, 'Tesla': {2023: {'Unnamed: 0': 3, 'Total Revenue': 96773, 'Net Income': 14974, 'Total Assets': 106618, 'Total Liabilities': 43009, 'Cash Flow from Operating Activities': 13256, 'Revenue Growth (%)': 0.0, 'Net Income Growth (%)': 0.0, 'Assets Growth (%)': 0.0, 'Liabilities Growth (%)': 0.0, 'Cash Flow from Operations Growth(%)': 0.0}, 2022: {'Unnamed: 0': 4, 'Total Revenue': 81462, 'Net Income': 12556, 'Total Assets': 82338, 'Total Liabilities': 36440, 'Cash Flow from Operating Activities': 14724, 'Revenue Growth (%)': -15.82, 'Net Income Growth (%)': -16.15, 'Assets Growth (%)': -22.77, 'Liabilities Growth (%)': -15.27, 'Cash Flow from Operations Growth(%)': 11.07}, 2021: {'Unnamed: 0': 5, 'Total Revenue': 53821, 'Net Income': 5519, 'Total Assets': 62131, 'Total Liabilities': 30548, 'Cash Flow from Operating Activities': 11497, 'Revenue Growth (%)': -33.93, 'Net Income Growth (%)': -56.04, 'Assets Growth (%)': -24.54, 'Liabilities Growth (%)': -16.17, 'Cash Flow from Operations Growth(%)': -21.92}}, 'Apple': {2023: {'Unnamed: 0': 6, 'Total Revenue': 383285, 'Net Income': 96995, 'Total Assets': 352583, 'Total Liabilities': 290437, 'Cash Flow from Operating Activities': 110543, 'Revenue Growth (%)': 0.0, 'Net Income Growth (%)': 0.0, 'Assets Growth (%)': 0.0, 'Liabilities Growth (%)': 0.0, 'Cash Flow from Operations Growth(%)': 0.0}, 2022: {'Unnamed: 0': 7, 'Total Revenue': 394328, 'Net Income': 99803, 'Total Assets': 352755, 'Total Liabilities': 302083, 'Cash Flow from Operating Activities': 122151, 'Revenue Growth (%)': 2.88, 'Net Income Growth (%)': 2.89, 'Assets Growth (%)': 0.05, 'Liabilities Growth (%)': 4.01, 'Cash Flow from Operations Growth(%)': 10.5}, 2021: {'Unnamed: 0': 8, 'Total Revenue': 365817, 'Net Income': 94680, 'Total Assets': 351002, 'Total Liabilities': 287912, 'Cash Flow from Operating Activities': 104038, 'Revenue Growth (%)': -7.23, 'Net Income Growth (%)': -5.13, 'Assets Growth (%)': -0.5, 'Liabilities Growth (%)': -4.69, 'Cash Flow from Operations Growth(%)': -14.83}}}
Welcome to the AI-powered financial chatbot!
We have fiscal data from 2021 to 2023 for Microsoft, Tesla, and Apple.
Which company's data do you want?: TesaL
Of which year?: 2023
1. Total Revenue
2. Total Net Income
3. Total Assets
4. Total Liabilities
5. Cash Flow from Operating Activities
6. Revenue Growth (%)
7. Net Income Growth (%)
Enter the metric's number you want to know: 5
Sorry, we don’t have data for TesaL in 2023.
Do you want to continue (yes/no)?: YES
Which company's data do you want?: Tesla
Of which year?: 2023
1. Total Revenue
2. Total Net Income
3. Total Assets
4. Total Liabilities
5. Cash Flow from Operating Activities
6. Revenue Growth (%)
7. Net Income Growth (%)
Enter the metric's number you want to know: 5

******************The Cash Flow from Operating Activities for Tesla in 2023 is: 13256**********

Do you want to continue (yes/no)?: no
Thank you!